# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-sync-docker-repos
  description: A GitHub action that syncs two docker repositories
  homepage: https://cloudposse.com/accelerate
  topics: ""
